// State Management
let currentLesson = null;
let currentStep = 0;
let totalXP = parseInt(localStorage.getItem('arabicXP') || '0');
let lessonsProgress = JSON.parse(localStorage.getItem('lessonsProgress') || '{}');

// Speech Synthesis
function speakArabic(text, element) {
    window.speechSynthesis.cancel();
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.lang = 'ar-SA';
    utterance.rate = 0.8;
    const voices = window.speechSynthesis.getVoices();
    const arabicVoice = voices.find(v => v.lang.startsWith('ar'));
    if (arabicVoice) utterance.voice = arabicVoice;
    if (element) {
        element.classList.add('speaking');
        utterance.onend = () => element.classList.remove('speaking');
    }
    window.speechSynthesis.speak(utterance);
}

function makeSpeakable(container) {
    const selectors = ['.arabic-word', '.vocab-arabic', '.exercise-arabic', 'span.arabic', '.grammar-box .arabic', '.warning-box .arabic'];
    selectors.forEach(selector => {
        container.querySelectorAll(selector).forEach(el => {
            if (!el.classList.contains('speakable') && el.textContent.trim()) {
                el.classList.add('speakable');
                el.title = 'Clique pour écouter';
                el.addEventListener('click', e => { e.stopPropagation(); speakArabic(el.textContent.trim(), el); });
            }
        });
    });
    container.querySelectorAll('.vocab-table td').forEach(el => {
        if (/[\u0600-\u06FF]/.test(el.textContent) && !el.classList.contains('speakable')) {
            el.classList.add('speakable');
            el.title = 'Clique pour écouter';
            el.addEventListener('click', e => { e.stopPropagation(); speakArabic(el.textContent.trim(), el); });
        }
    });
}

if ('speechSynthesis' in window) window.speechSynthesis.onvoiceschanged = () => window.speechSynthesis.getVoices();

document.addEventListener('DOMContentLoaded', () => { updateXPDisplay(); updateProgressBars(); });

// Lessons Data
const lessonsData = {
    1: {
        title: "الدرس الأول - Les noms démonstratifs (هذا)",
        xp: 50,
        steps: [
            { type: "theory", content: `<div class="audio-hint"><span class="audio-hint-icon">🔊</span><span>Clique sur les mots arabes pour entendre leur prononciation !</span></div><div class="theory-section"><h3 class="theory-title">📚 Introduction aux types de mots</h3><div class="theory-content"><p>En arabe, les mots (الكَلِمَةُ) se divisent en <strong>trois catégories</strong> :</p><div class="grammar-box"><h4>📝 Les trois types de mots</h4><table class="vocab-table"><thead><tr><th>Arabe</th><th>Français</th><th>Définition</th></tr></thead><tbody><tr><td class="vocab-arabic arabic">اِسْمٌ</td><td>Nom</td><td>Indique un sens par lui-même</td></tr><tr><td class="vocab-arabic arabic">فِعْلٌ</td><td>Verbe</td><td>Indique une action et un temps</td></tr><tr><td class="vocab-arabic arabic">حَرْفٌ</td><td>Particule</td><td>N'a de sens qu'avec un autre mot</td></tr></tbody></table></div></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Le démonstratif هذا</h3><div class="theory-content"><div class="arabic-example"><div class="arabic-word arabic">هَذَا</div><div class="arabic-translation">Ceci / Celui-ci</div></div><p><span class="arabic">هَذَا</span> est un <strong>nom démonstratif</strong> (اِسْمُ إشَارَةٍ). Il s'utilise pour :</p><div class="grammar-box"><h4>✅ Conditions d'utilisation</h4><ul style="list-style:none;padding:0;"><li>• <strong class="arabic">مُفْرَد</strong> - Singulier</li><li>• <strong class="arabic">مُذَكَّر</strong> - Masculin</li><li>• <strong class="arabic">قَرِيب</strong> - Proche</li></ul></div><div class="arabic-example"><div class="arabic-word arabic">هَذَا كَلْبٌ</div><div class="arabic-translation">Ceci est un chien</div></div></div></div>` },
            { type: "exercise", content: `<div class="exercise-section"><h3 class="exercise-title">🎯 Exercice pratique</h3><div class="exercise-question"><p>Comment dit-on "Ceci est un livre" en arabe ?</p></div><div class="options-grid"><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">ذلِكَ كِتَابٌ</span></button><button class="option-btn" data-correct="true" onclick="checkAnswer(this)"><span class="arabic">هَذَا كِتَابٌ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">مَا كِتَابٌ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">مَنْ كِتَابٌ</span></button></div><div class="feedback-message" id="feedback"></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Vocabulaire : Singulier et Pluriel</h3><div class="theory-content"><div class="warning-box"><h4>⚠️ Particularité orthographique</h4><p>Le alif après le ه se prononce mais ne s'écrit pas :</p><div class="arabic-example"><div class="arabic-word arabic">هَذَا = هَاذَا</div></div></div><table class="vocab-table"><thead><tr><th>Singulier</th><th>Pluriel</th><th>Traduction</th></tr></thead><tbody><tr><td class="vocab-arabic arabic">كِتَابٌ</td><td class="vocab-arabic arabic">كُتُبٌ</td><td>Livre(s)</td></tr><tr><td class="vocab-arabic arabic">مَسْجِدٌ</td><td class="vocab-arabic arabic">مَسَاجِدُ</td><td>Mosquée(s)</td></tr><tr><td class="vocab-arabic arabic">بَيْتٌ</td><td class="vocab-arabic arabic">بُيُوتٌ</td><td>Maison(s)</td></tr><tr><td class="vocab-arabic arabic">قَلَمٌ</td><td class="vocab-arabic arabic">أَقْلَامٌ</td><td>Stylo(s)</td></tr></tbody></table></div></div>` },
            { type: "exercise", content: `<div class="exercise-section"><h3 class="exercise-title">🎯 Exercice final</h3><div class="exercise-question"><p>Quel est le pluriel de <span class="arabic" style="font-size:1.5rem;color:var(--primary);">بَابٌ</span> (porte) ?</p></div><div class="options-grid"><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">بُيُوتٌ</span></button><button class="option-btn" data-correct="true" onclick="checkAnswer(this)"><span class="arabic">أَبْوَابٌ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">كُتُبٌ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">مَفَاتِحُ</span></button></div><div class="feedback-message" id="feedback"></div></div>` }
        ]
    },
    2: {
        title: "الدرس الثاني - L'interrogatif",
        xp: 60,
        steps: [
            { type: "theory", content: `<div class="audio-hint"><span class="audio-hint-icon">🔊</span><span>Clique sur les mots arabes pour entendre leur prononciation !</span></div><div class="theory-section"><h3 class="theory-title">📚 L'interrogatif (الاِسْتِفْهَامُ)</h3><div class="theory-content"><p>Pour poser des questions en arabe :</p><div class="grammar-box"><h4>📝 Les particules et noms interrogatifs</h4><table class="vocab-table"><thead><tr><th>Arabe</th><th>Type</th><th>Traduction</th></tr></thead><tbody><tr><td class="vocab-arabic arabic">أَ</td><td>Particule</td><td>Est-ce que ?</td></tr><tr><td class="vocab-arabic arabic">مَا</td><td>Nom</td><td>Qu'est-ce que ?</td></tr><tr><td class="vocab-arabic arabic">مَنْ</td><td>Nom</td><td>Qui est-ce ?</td></tr></tbody></table></div></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 La hamza interrogative (أَ)</h3><div class="theory-content"><div class="arabic-example"><div class="arabic-word arabic">أَ</div><div class="arabic-translation">Est-ce que ?</div></div><div class="grammar-box"><h4>✅ Comment répondre ?</h4><ul style="list-style:none;padding:0;"><li>• <span class="arabic" style="color:var(--success);font-size:1.3rem;">نَعَمْ</span> - Oui</li><li>• <span class="arabic" style="color:var(--accent);font-size:1.3rem;">لَا</span> - Non</li></ul></div><div class="arabic-example"><div class="arabic-word arabic">أَهَذَا كِتَابٌ؟</div><div class="arabic-translation">Est-ce que ceci est un livre ?</div></div></div></div>` },
            { type: "exercise", content: `<div class="exercise-section"><h3 class="exercise-title">🎯 Exercice pratique</h3><div class="exercise-question"><p class="arabic" style="font-size:2rem;color:var(--primary);">أَهَذَا بَيْتٌ؟</p><p>(En regardant une mosquée)</p></div><div class="options-grid"><button class="option-btn" data-correct="true" onclick="checkAnswer(this)"><span class="arabic">لَا، هَذَا مَسْجِدٌ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">نَعَمْ، هَذَا بَيْتٌ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">مَا هَذَا</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">مَنْ هَذَا</span></button></div><div class="feedback-message" id="feedback"></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 مَا vs مَنْ</h3><div class="theory-content"><div class="grammar-box"><h4>🔑 Différence clé</h4><table class="vocab-table"><thead><tr><th>Interrogatif</th><th>Utilisation</th><th>Exemple</th></tr></thead><tbody><tr><td class="vocab-arabic arabic">مَا</td><td>Non-humain</td><td class="vocab-arabic arabic">مَا هَذَا؟ هَذَا كَلْبٌ</td></tr><tr><td class="vocab-arabic arabic">مَنْ</td><td>Humain</td><td class="vocab-arabic arabic">مَنْ هَذَا؟ هَذَا طَبِيبٌ</td></tr></tbody></table></div></div></div>` },
            { type: "exercise", content: `<div class="exercise-section"><h3 class="exercise-title">🎯 Exercice pratique</h3><div class="exercise-question"><p>Pour demander "Qui est cet enseignant ?", j'utilise :</p></div><div class="options-grid"><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">مَا هَذَا المُدَرِّسُ؟</span></button><button class="option-btn" data-correct="true" onclick="checkAnswer(this)"><span class="arabic">مَنْ هَذَا المُدَرِّسُ؟</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">أَهَذَا مُدَرِّسٌ؟</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">هَذَا مُدَرِّسٌ</span></button></div><div class="feedback-message" id="feedback"></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Vocabulaire</h3><div class="theory-content"><table class="vocab-table"><thead><tr><th>Singulier</th><th>Pluriel</th><th>Traduction</th></tr></thead><tbody><tr><td class="vocab-arabic arabic">طَبِيبٌ</td><td class="vocab-arabic arabic">أَطِبَّاءُ</td><td>Médecin(s)</td></tr><tr><td class="vocab-arabic arabic">مُدَرِّسٌ</td><td class="vocab-arabic arabic">مُدَرِّسُونَ</td><td>Enseignant(s)</td></tr><tr><td class="vocab-arabic arabic">طَالِبٌ</td><td class="vocab-arabic arabic">طُلَّابٌ</td><td>Étudiant(s)</td></tr><tr><td class="vocab-arabic arabic">كَلْبٌ</td><td class="vocab-arabic arabic">كِلَابٌ</td><td>Chien(s)</td></tr></tbody></table></div></div>` }
        ]
    },
    3: {
        title: "الدرس الثالث - Le démonstratif éloigné (ذلك)",
        xp: 50,
        steps: [
            { type: "theory", content: `<div class="audio-hint"><span class="audio-hint-icon">🔊</span><span>Clique sur les mots arabes pour entendre leur prononciation !</span></div><div class="theory-section"><h3 class="theory-title">📚 Le démonstratif ذَلِكَ</h3><div class="theory-content"><div class="arabic-example"><div class="arabic-word arabic">ذَلِكَ</div><div class="arabic-translation">Cela / Celui-là</div></div><p><span class="arabic">ذَلِكَ</span> s'utilise pour désigner quelque chose qui est :</p><div class="grammar-box"><h4>✅ Conditions d'utilisation</h4><ul style="list-style:none;padding:0;"><li>• <strong class="arabic">مُفْرَد</strong> - Singulier</li><li>• <strong class="arabic">مُذَكَّر</strong> - Masculin</li><li>• <strong class="arabic" style="color:var(--accent);">بَعِيد</strong> - <strong>Éloigné</strong></li></ul></div><div class="arabic-example"><div class="arabic-word arabic">ذَلِكَ نَجْمٌ</div><div class="arabic-translation">Cela est une étoile (loin)</div></div></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Différence entre هَذَا et ذَلِكَ</h3><div class="theory-content"><div class="grammar-box"><h4>🔑 La seule différence : la distance</h4><table class="vocab-table"><thead><tr><th>Démonstratif</th><th>Distance</th><th>Exemple</th></tr></thead><tbody><tr><td class="vocab-arabic arabic" style="color:var(--success);">هَذَا</td><td style="color:var(--success);">Proche</td><td class="vocab-arabic arabic">هَذَا مَسْجِدٌ</td></tr><tr><td class="vocab-arabic arabic" style="color:var(--accent);">ذَلِكَ</td><td style="color:var(--accent);">Éloigné</td><td class="vocab-arabic arabic">ذَلِكَ بَيْتٌ</td></tr></tbody></table></div></div></div>` },
            { type: "exercise", content: `<div class="exercise-section"><h3 class="exercise-title">🎯 Exercice pratique</h3><div class="exercise-question"><p>Tu vois une étoile dans le ciel (loin). Comment dis-tu "Cela est une étoile" ?</p></div><div class="options-grid"><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">هَذَا نَجْمٌ</span></button><button class="option-btn" data-correct="true" onclick="checkAnswer(this)"><span class="arabic">ذَلِكَ نَجْمٌ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">مَا نَجْمٌ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">مَنْ نَجْمٌ</span></button></div><div class="feedback-message" id="feedback"></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Vocabulaire supplémentaire</h3><div class="theory-content"><table class="vocab-table"><thead><tr><th>Singulier</th><th>Pluriel</th><th>Traduction</th></tr></thead><tbody><tr><td class="vocab-arabic arabic">إِمَامٌ</td><td class="vocab-arabic arabic">أَئِمَّةٌ</td><td>Imam(s)</td></tr><tr><td class="vocab-arabic arabic">سُكَّرٌ</td><td class="vocab-arabic arabic">-</td><td>Sucre</td></tr><tr><td class="vocab-arabic arabic">حَجَرٌ</td><td class="vocab-arabic arabic">حِجَارٌ</td><td>Pierre(s)</td></tr><tr><td class="vocab-arabic arabic">لَبَنٌ</td><td class="vocab-arabic arabic">أَلْبَانٌ</td><td>Lait(s)</td></tr></tbody></table></div></div>` },
            { type: "exercise", content: `<div class="exercise-section"><h3 class="exercise-title">🎯 Exercice final</h3><div class="exercise-question"><p>"Ceci est du sucre (proche) et cela est du lait (loin)"</p></div><div class="options-grid"><button class="option-btn" data-correct="true" onclick="checkAnswer(this)"><span class="arabic">هَذَا سُكَّرٌ وَذَلِكَ لَبَنٌ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">ذَلِكَ سُكَّرٌ وَهَذَا لَبَنٌ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">هَذَا سُكَّرٌ وَهَذَا لَبَنٌ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">ذَلِكَ سُكَّرٌ وَذَلِكَ لَبَنٌ</span></button></div><div class="feedback-message" id="feedback"></div></div>` }
        ]
    },
    4: {
        title: "الدرس الرابع - Le défini et l'indéfini",
        xp: 70,
        steps: [
            { type: "theory", content: `<div class="audio-hint"><span class="audio-hint-icon">🔊</span><span>Clique sur les mots arabes pour entendre leur prononciation !</span></div><div class="theory-section"><h3 class="theory-title">📚 L'indéfini et le défini</h3><div class="theory-content"><div class="grammar-box"><h4>📝 L'indéfini (النَّكِرَة)</h4><ul style="list-style:none;padding:0;"><li>• Base du nom</li><li>• Non désigné</li><li>• Tanwin (ٌ ً ٍ)</li></ul></div><div class="warning-box"><h4>⚠️ Le défini (المَعْرِفَة)</h4><ul style="list-style:none;padding:0;"><li>• Déterminé</li><li>• Article <span class="arabic" style="color:var(--primary);">ال</span></li><li>• Perd le tanwin</li></ul></div><div class="arabic-example"><div class="arabic-word arabic">كِتَابٌ → الكِتَابُ</div><div class="arabic-translation">un livre → le livre</div></div></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 L'article défini (ال)</h3><div class="theory-content"><p>L'article <span class="arabic" style="font-size:1.5em;color:var(--primary);">ال</span> = ا (hamza de liaison) + ل</p><div class="warning-box"><h4>⚠️ Important</h4><p>La hamza de liaison ne se prononce qu'en <strong>début de phrase</strong> !</p><div class="arabic-example"><p class="arabic" style="font-size:1.3rem;">اَلْكِتَابُ جَدِيدٌ</p><p class="arabic-translation">Le livre est nouveau (début)</p><p class="arabic" style="font-size:1.3rem;margin-top:0.5rem;">هَذَا الْكِتَابُ</p><p class="arabic-translation">Ce livre (milieu - hamza non prononcée)</p></div></div></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Les lettres lunaires 🌙</h3><div class="theory-content"><p>Devant ces lettres, le <strong>لام se prononce</strong> :</p><div class="grammar-box"><h4>📝 Les 14 lettres lunaires</h4><p class="arabic" style="font-size:1.5rem;text-align:center;">أ ب ج ح خ ع غ ف ق ك م و هـ ي</p></div><table class="vocab-table"><thead><tr><th>Lettre</th><th>Exemple</th><th>Prononciation</th></tr></thead><tbody><tr><td class="vocab-arabic arabic">ب</td><td class="vocab-arabic arabic">البَابُ</td><td>al-bāb</td></tr><tr><td class="vocab-arabic arabic">ك</td><td class="vocab-arabic arabic">الكِتَابُ</td><td>al-kitāb</td></tr><tr><td class="vocab-arabic arabic">ق</td><td class="vocab-arabic arabic">القَمَرُ</td><td>al-qamar</td></tr></tbody></table></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Les lettres solaires ☀️</h3><div class="theory-content"><p>Devant ces lettres, le <strong>لام NE se prononce PAS</strong> (lettre doublée) :</p><div class="warning-box"><h4>⚠️ Les 14 lettres solaires</h4><p class="arabic" style="font-size:1.5rem;text-align:center;">ت ث د ذ ر ز س ش ص ض ط ظ ل ن</p></div><table class="vocab-table"><thead><tr><th>Lettre</th><th>Exemple</th><th>Prononciation</th></tr></thead><tbody><tr><td class="vocab-arabic arabic">ش</td><td class="vocab-arabic arabic">الشَّمْسُ</td><td>ash-shams</td></tr><tr><td class="vocab-arabic arabic">ر</td><td class="vocab-arabic arabic">الرَّجُلُ</td><td>ar-rajul</td></tr><tr><td class="vocab-arabic arabic">ن</td><td class="vocab-arabic arabic">النَّجْمُ</td><td>an-najm</td></tr></tbody></table></div></div>` },
            { type: "exercise", content: `<div class="exercise-section"><h3 class="exercise-title">🎯 Exercice pratique</h3><div class="exercise-question"><p>Dans <span class="arabic" style="font-size:1.5em;">الشَّمْسُ</span>, le لام se prononce-t-il ?</p></div><div class="options-grid"><button class="option-btn" data-correct="false" onclick="checkAnswer(this)">Oui, car ش est lunaire</button><button class="option-btn" data-correct="true" onclick="checkAnswer(this)">Non, car ش est solaire</button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)">Oui, toujours</button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)">Non, jamais</button></div><div class="feedback-message" id="feedback"></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Vocabulaire nouveau</h3><div class="theory-content"><table class="vocab-table"><thead><tr><th>Singulier</th><th>Pluriel</th><th>Traduction</th></tr></thead><tbody><tr><td class="vocab-arabic arabic">مَاءٌ</td><td class="vocab-arabic arabic">مِيَاهٌ</td><td>Eau</td></tr><tr><td class="vocab-arabic arabic">جَدِيدٌ</td><td class="vocab-arabic arabic">جُدُدٌ</td><td>Nouveau</td></tr><tr><td class="vocab-arabic arabic">مَفْتُوحٌ</td><td>-</td><td>Ouvert</td></tr><tr><td class="vocab-arabic arabic">شَمْسٌ</td><td class="vocab-arabic arabic">شُمُوسٌ</td><td>Soleil</td></tr><tr><td class="vocab-arabic arabic">قَمَرٌ</td><td class="vocab-arabic arabic">أَقْمَارٌ</td><td>Lune</td></tr></tbody></table></div></div>` },
            { type: "exercise", content: `<div class="exercise-section"><h3 class="exercise-title">🎯 Exercice final</h3><div class="exercise-question"><p>"Le livre est nouveau et la porte est ouverte"</p></div><div class="options-grid"><button class="option-btn" data-correct="true" onclick="checkAnswer(this)"><span class="arabic">الكِتَابُ جَدِيدٌ وَالبَابُ مَفْتُوحٌ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">كِتَابٌ جَدِيدٌ وَبَابٌ مَفْتُوحٌ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">هَذَا كِتَابٌ وَهَذَا بَابٌ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">الكِتَابُ مَفْتُوحٌ وَالبَابُ جَدِيدٌ</span></button></div><div class="feedback-message" id="feedback"></div></div>` }
        ]
    },
    5: {
        title: "الدرس الخامس - Les prépositions (حُرُوفُ الجَرِّ)",
        xp: 60,
        steps: [
            { type: "theory", content: `<div class="audio-hint"><span class="audio-hint-icon">🔊</span><span>Clique sur les mots arabes pour entendre leur prononciation !</span></div><div class="theory-section"><h3 class="theory-title">📚 Introduction : الإِعْرَابُ (la flexion)</h3><div class="theory-content"><p>En arabe, les terminaisons des mots peuvent <strong>varier</strong>. Cette variation s'appelle <span class="arabic" style="color:var(--primary);font-size:1.3em;">الإِعْرَابُ</span>.</p><div class="arabic-example"><p class="arabic" style="font-size:1.5rem;">هَذَا كِتَابٌ</p><p class="arabic-translation">Ceci est un livre (nominatif : ٌ)</p><p class="arabic" style="font-size:1.5rem;margin-top:0.5rem;">قَرَأْتُ كِتَابًا</p><p class="arabic-translation">J'ai lu un livre (accusatif : ً)</p><p class="arabic" style="font-size:1.5rem;margin-top:0.5rem;">هَذَا فِي الكِتَابِ</p><p class="arabic-translation">Ceci est dans le livre (génitif : ِ)</p></div></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Les prépositions (حُرُوفُ الجَرِّ)</h3><div class="theory-content"><div class="arabic-example"><div class="arabic-word arabic">حُرُوفُ الجَرِّ</div><div class="arabic-translation">Les prépositions</div></div><div class="grammar-box"><h4>📝 Le rôle de la préposition</h4><ul style="list-style:none;padding:0;"><li>• Elle agit sur le <strong>sens</strong> d'un nom qui la suit</li><li>• Elle agit sur la <strong>voyelle finale</strong></li><li>• Le nom devient <strong>مَجْرُور</strong> (génitif) avec une <span class="arabic" style="color:var(--primary);">كَسْرَة</span> (ِ)</li></ul></div><div class="arabic-example"><div class="arabic-word arabic">الكِتَابُ : فِي + الكِتَابُ = فِي الكِتَابِ</div><div class="arabic-translation">Le livre + في = dans le livre (ُ → ِ)</div></div></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Les principales prépositions</h3><div class="theory-content"><table class="vocab-table"><thead><tr><th>Préposition</th><th>Sens</th><th>Exemple</th><th>Traduction</th></tr></thead><tbody><tr><td class="vocab-arabic arabic" style="font-size:2rem;">فِي</td><td>Dans (lieu/temps)</td><td class="vocab-arabic arabic">فِي البَيْتِ</td><td>Dans la maison</td></tr><tr><td class="vocab-arabic arabic" style="font-size:2rem;">عَلَى</td><td>Sur</td><td class="vocab-arabic arabic">عَلَى الطَّاوِلَةِ</td><td>Sur la table</td></tr><tr><td class="vocab-arabic arabic" style="font-size:2rem;">مِنْ</td><td>De (provenance)</td><td class="vocab-arabic arabic">مِنَ المَسْجِدِ</td><td>De la mosquée</td></tr><tr><td class="vocab-arabic arabic" style="font-size:2rem;">إِلَى</td><td>Vers</td><td class="vocab-arabic arabic">إِلَى المَسْجِدِ</td><td>Vers la mosquée</td></tr></tbody></table></div></div>` },
            { type: "exercise", content: `<div class="exercise-section"><h3 class="exercise-title">🎯 Exercice pratique</h3><div class="exercise-question"><p>Comment dit-on "dans la maison" ?</p></div><div class="options-grid"><button class="option-btn" data-correct="true" onclick="checkAnswer(this)"><span class="arabic">فِي البَيْتِ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">فِي البَيْتُ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">عَلَى البَيْتِ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">مِنَ البَيْتِ</span></button></div><div class="feedback-message" id="feedback"></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 أَيْنَ - Où ?</h3><div class="theory-content"><div class="arabic-example"><div class="arabic-word arabic">أَيْنَ</div><div class="arabic-translation">Où ? (Où est-ce ?)</div></div><div class="grammar-box"><h4>📝 Caractéristiques de أَيْنَ</h4><p><span class="arabic">أَيْنَ</span> est un <strong>nom interrogatif</strong> (اِسْمُ اسْتِفْهَامٍ) exclusif pour les <strong>lieux</strong>.</p></div><div class="arabic-example"><p class="arabic" style="font-size:1.5rem;">أَيْنَ الكِتَابُ؟</p><p class="arabic-translation">Où est le livre ?</p><p class="arabic" style="font-size:1.5rem;margin-top:0.5rem;">هُوَ عَلَى المَكْتَبِ</p><p class="arabic-translation">Il est sur le bureau</p></div><div class="arabic-example" style="margin-top:1rem;"><p class="arabic" style="font-size:1.5rem;">أَيْنَ مُحَمَّدٌ؟</p><p class="arabic-translation">Où est Mohammed ?</p><p class="arabic" style="font-size:1.5rem;margin-top:0.5rem;">هُوَ فِي الغُرْفَةِ</p><p class="arabic-translation">Il est dans la chambre</p></div></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Vocabulaire : Les lieux de la maison</h3><div class="theory-content"><table class="vocab-table"><thead><tr><th>Arabe</th><th>Traduction</th><th>Exemple</th></tr></thead><tbody><tr><td class="vocab-arabic arabic">الغُرْفَةُ</td><td>La chambre</td><td class="vocab-arabic arabic">فِي الغُرْفَةِ</td></tr><tr><td class="vocab-arabic arabic">الحَمَّامُ</td><td>La salle de bain</td><td class="vocab-arabic arabic">فِي الحَمَّامِ</td></tr><tr><td class="vocab-arabic arabic">المَطْبَخُ</td><td>La cuisine</td><td class="vocab-arabic arabic">فِي المَطْبَخِ</td></tr><tr><td class="vocab-arabic arabic">المَكْتَبُ</td><td>Le bureau</td><td class="vocab-arabic arabic">عَلَى المَكْتَبِ</td></tr><tr><td class="vocab-arabic arabic">السَّرِيرُ</td><td>Le lit</td><td class="vocab-arabic arabic">عَلَى السَّرِيرِ</td></tr><tr><td class="vocab-arabic arabic">الكُرْسِيُّ</td><td>La chaise</td><td class="vocab-arabic arabic">عَلَى الكُرْسِيِّ</td></tr><tr><td class="vocab-arabic arabic">الطَّاوِلَةُ</td><td>La table</td><td class="vocab-arabic arabic">عَلَى الطَّاوِلَةِ</td></tr></tbody></table></div></div>` },
            { type: "exercise", content: `<div class="exercise-section"><h3 class="exercise-title">🎯 Exercice final</h3><div class="exercise-question"><p class="arabic" style="font-size:2rem;color:var(--primary);">أَيْنَ الكِتَابُ؟</p><p>Le livre est sur le bureau. Quelle est la bonne réponse ?</p></div><div class="options-grid"><button class="option-btn" data-correct="true" onclick="checkAnswer(this)"><span class="arabic">هُوَ عَلَى المَكْتَبِ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">هُوَ فِي المَكْتَبِ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">هُوَ عَلَى المَكْتَبُ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">هُوَ مِنَ المَكْتَبِ</span></button></div><div class="feedback-message" id="feedback"></div></div>` }
        ]
    },
    6: {
        title: "الدرس السادس - Les noms propres (العَلَمُ)",
        xp: 65,
        steps: [
            { type: "theory", content: `<div class="audio-hint"><span class="audio-hint-icon">🔊</span><span>Clique sur les mots arabes pour entendre leur prononciation !</span></div><div class="theory-section"><h3 class="theory-title">📚 Les noms propres (العَلَمُ)</h3><div class="theory-content"><div class="arabic-example"><div class="arabic-word arabic">العَلَمُ</div><div class="arabic-translation">Le nom propre</div></div><p>Les noms propres en arabe désignent :</p><div class="grammar-box"><h4>📝 Caractéristiques des noms propres</h4><ul style="list-style:none;padding:0;"><li>• Une <strong>personne en particulier</strong> ou un <strong>lieu précis</strong></li><li>• Toujours <strong>défini</strong> (<span class="arabic">مَعْرِفَةٌ</span>)</li><li>• Peut être <strong>masculin ou féminin</strong> (<span class="arabic">مُذَكَّرٌ وَمُؤَنَّثٌ</span>)</li></ul></div><div class="arabic-example"><p class="arabic" style="font-size:1.5rem;">هَذَا مُحَمَّدٌ</p><p class="arabic-translation">Ceci est Mohammed</p><p class="arabic" style="font-size:1.5rem;margin-top:0.5rem;">فَاطِمَةُ فِي المَسْجِدِ</p><p class="arabic-translation">Fatima est dans la mosquée</p></div></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Les types de noms définis (المَعَارِفُ)</h3><div class="theory-content"><div class="grammar-box"><h4>📝 Les 3 types de noms définis</h4><table class="vocab-table"><thead><tr><th>Type</th><th>Arabe</th><th>Exemple</th></tr></thead><tbody><tr><td>Défini par ال</td><td class="vocab-arabic arabic">المُعَرَّفُ بِال</td><td class="vocab-arabic arabic">الكِتَابُ</td></tr><tr><td>Noms démonstratifs</td><td class="vocab-arabic arabic">أَسْمَاءُ الإِشَارَةِ</td><td class="vocab-arabic arabic">هَذَا ، ذَلِكَ</td></tr><tr><td>Noms propres</td><td class="vocab-arabic arabic">العَلَمُ</td><td class="vocab-arabic arabic">مُحَمَّدٌ ، مَكَّةُ</td></tr></tbody></table></div></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Le tanwin (التَّنْوِينُ)</h3><div class="theory-content"><div class="arabic-example"><div class="arabic-word arabic">التَّنْوِينُ</div><div class="arabic-translation">Le tanwin</div></div><p>Le tanwin est un <strong>noun (ن) qui se prononce à la fin du nom mais ne s'écrit pas</strong>.</p><div class="grammar-box"><h4>📝 Exemples</h4><p class="arabic" style="font-size:1.5rem;text-align:center;">مُحَمَّدٌ = مُحَمَّدُنْ</p><p class="arabic" style="font-size:1.5rem;text-align:center;margin-top:0.5rem;">زَيْدٌ = زَيْدُنْ</p></div><div class="warning-box"><h4>⚠️ Exception importante</h4><p>Certains noms n'acceptent pas le tanwin : <span class="arabic" style="color:var(--accent);">مَمْنُوعٌ مِنَ الصَّرْفِ</span></p><p>Notamment les <strong>noms propres féminins</strong> :</p><p class="arabic" style="font-size:1.3rem;text-align:center;margin-top:0.5rem;">عَائِشَةُ ، زَيْنَبُ ، فَاطِمَةُ ، مَكَّةُ</p></div></div></div>` },
            { type: "exercise", content: `<div class="exercise-section"><h3 class="exercise-title">🎯 Exercice pratique</h3><div class="exercise-question"><p>Quel nom propre prend le tanwin ?</p></div><div class="options-grid"><button class="option-btn" data-correct="true" onclick="checkAnswer(this)"><span class="arabic">مُحَمَّدٌ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">فَاطِمَةُ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">عَائِشَةُ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">مَكَّةُ</span></button></div><div class="feedback-message" id="feedback"></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 مِنْ أَيْنَ ؟ - D'où ?</h3><div class="theory-content"><div class="arabic-example"><div class="arabic-word arabic">مِنْ أَيْنَ أَنْتَ ؟</div><div class="arabic-translation">D'où viens-tu ?</div></div><p>La combinaison de <span class="arabic" style="color:var(--primary);">مِنْ</span> (préposition "de") + <span class="arabic" style="color:var(--primary);">أَيْنَ</span> (où) permet de demander l'origine.</p><div class="grammar-box"><h4>📝 Exemples</h4><div class="arabic-example"><p class="arabic" style="font-size:1.3rem;">مِنْ أَيْنَ أَنْتَ صَدِيقِي ؟ أَنَا مِنْ فَرَنْسَا</p><p class="arabic-translation">D'où viens-tu mon ami ? Je viens de France</p><p class="arabic" style="font-size:1.3rem;margin-top:0.5rem;">مِنْ أَيْنَ قَمِيصُكَ ؟ هُوَ مِنْ مَكَّةَ</p><p class="arabic-translation">D'où vient ta chemise ? Elle vient de La Mecque</p></div></div></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Vocabulaire : Pays et lieux</h3><div class="theory-content"><table class="vocab-table"><thead><tr><th>Arabe</th><th>Français</th></tr></thead><tbody><tr><td class="vocab-arabic arabic">فَرَنْسَا</td><td>La France</td></tr><tr><td class="vocab-arabic arabic">اليَابَانُ</td><td>Le Japon</td></tr><tr><td class="vocab-arabic arabic">الصِّينُ</td><td>La Chine</td></tr><tr><td class="vocab-arabic arabic">الهِنْدُ</td><td>L'Inde</td></tr><tr><td class="vocab-arabic arabic">إِفْرِيقِيَا</td><td>L'Afrique</td></tr><tr><td class="vocab-arabic arabic">مَدْرَسَةٌ</td><td>École</td></tr><tr><td class="vocab-arabic arabic">جَامِعَةٌ</td><td>Université</td></tr><tr><td class="vocab-arabic arabic">سُوقٌ</td><td>Marché</td></tr></tbody></table></div></div>` },
            { type: "exercise", content: `<div class="exercise-section"><h3 class="exercise-title">🎯 Exercice final</h3><div class="exercise-question"><p class="arabic" style="font-size:2rem;color:var(--primary);">مِنْ أَيْنَ أَنْتَ ؟</p><p>Tu viens du Japon. Quelle est la bonne réponse ?</p></div><div class="options-grid"><button class="option-btn" data-correct="true" onclick="checkAnswer(this)"><span class="arabic">أَنَا مِنَ اليَابَانِ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">أَنَا فِي اليَابَانِ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">أَنَا إِلَى اليَابَانِ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">أَنَا مِنَ اليَابَانُ</span></button></div><div class="feedback-message" id="feedback"></div></div>` }
        ]
    },
    7: {
        title: "الدرس السابع - L'annexion approfondie (الإِضَافَةُ)",
        xp: 80,
        steps: [
            { type: "theory", content: `<div class="audio-hint"><span class="audio-hint-icon">🔊</span><span>Clique sur les mots arabes pour entendre leur prononciation !</span></div><div class="theory-section"><h3 class="theory-title">📚 Révision : Les 3 cas (الإِعْرَابُ)</h3><div class="theory-content"><div class="grammar-box"><h4>📝 Rappel des 3 déclinaisons</h4><table class="vocab-table"><thead><tr><th>Cas</th><th>Arabe</th><th>Marque</th><th>Nom décliné</th></tr></thead><tbody><tr><td style="color:var(--success);">Nominatif</td><td class="vocab-arabic arabic">الرَّفْعُ</td><td>ُ (ضَمَّة)</td><td class="vocab-arabic arabic">مَرْفُوعٌ</td></tr><tr><td style="color:var(--warning);">Accusatif</td><td class="vocab-arabic arabic">النَّصْبُ</td><td>َ (فَتْحَة)</td><td class="vocab-arabic arabic">مَنْصُوبٌ</td></tr><tr><td style="color:var(--accent);">Génitif</td><td class="vocab-arabic arabic">الجَرُّ</td><td>ِ (كَسْرَة)</td><td class="vocab-arabic arabic">مَجْرُورٌ</td></tr></tbody></table></div></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Le nominatif en pratique</h3><div class="theory-content"><div class="arabic-example"><div class="arabic-word arabic">الرَّفْعُ</div><div class="arabic-translation">C'est la base dans الإِعْرَاب</div></div><div class="grammar-box"><h4>📝 Quand utiliser le nominatif ?</h4><ul style="list-style:none;padding:0;"><li>• Pour le <strong>sujet</strong> de la phrase</li><li>• Pour le <strong>prédicat</strong> (خبر)</li><li>• Cas par défaut</li></ul></div><div class="arabic-example"><p class="arabic" style="font-size:1.8rem;">هَذَا <span style="color:var(--success);">مُحَمَّدٌ</span></p><p class="arabic-translation">Ceci est Mohammed</p><p style="margin-top:0.5rem;"><span class="arabic">مُحَمَّدٌ</span> = <span style="color:var(--success);">اِسْمٌ مَرْفُوعٌ</span></p></div></div></div>` },
            { type: "exercise", content: `<div class="exercise-section"><h3 class="exercise-title">🎯 Exercice pratique</h3><div class="exercise-question"><p>Quelle est la marque du nominatif (الرَّفْعُ) ?</p></div><div class="options-grid"><button class="option-btn" data-correct="true" onclick="checkAnswer(this)"><span class="arabic">الضَّمَّةُ</span> (ُ)</button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">الفَتْحَةُ</span> (َ)</button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">الكَسْرَةُ</span> (ِ)</button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">السُّكُونُ</span> (ْ)</button></div><div class="feedback-message" id="feedback"></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 L'annexion détaillée (الإِضَافَةُ)</h3><div class="theory-content"><div class="arabic-example"><div class="arabic-word arabic">الإِضَافَةُ</div><div class="arabic-translation">L'annexion = exprimer la possession</div></div><p>L'annexion associe <strong>deux noms</strong> : le possédé (مُضَاف) et le possesseur (مُضَاف إِلَيْهِ).</p><div class="warning-box"><h4>⚠️ Règles essentielles</h4><ul style="list-style:none;padding:0;"><li>• <span class="arabic">المُضَافُ</span> : <strong>JAMAIS</strong> de ال ni de tanwin</li><li>• <span class="arabic">المُضَافُ إِلَيْهِ</span> : <strong>TOUJOURS</strong> مَجْرُور (kasra)</li></ul></div></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Exemples pratiques</h3><div class="theory-content"><div class="arabic-example"><p class="arabic" style="font-size:1.8rem;"><span style="color:var(--primary);">كِتَابُ</span> <span style="color:var(--accent);">مُحَمَّدٍ</span></p><p class="arabic-translation">Le livre de Mohammed</p><p style="font-size:0.9rem;">كِتَابُ = مُضَاف (pas de ال, pas de tanwin)</p><p style="font-size:0.9rem;">مُحَمَّدٍ = مُضَاف إِلَيْهِ مَجْرُور</p></div><div class="arabic-example" style="margin-top:1rem;"><p class="arabic" style="font-size:1.8rem;"><span style="color:var(--primary);">بَيْتُ</span> <span style="color:var(--accent);">اللهِ</span></p><p class="arabic-translation">La maison d'Allah (la Ka'ba)</p></div><div class="arabic-example" style="margin-top:1rem;"><p class="arabic" style="font-size:1.8rem;"><span style="color:var(--primary);">حَقِيبَةُ</span> <span style="color:var(--accent);">المُدَرِّسِ</span></p><p class="arabic-translation">Le sac de l'enseignant</p></div></div></div>` },
            { type: "exercise", content: `<div class="exercise-section"><h3 class="exercise-title">🎯 Exercice pratique</h3><div class="exercise-question"><p>Comment forme-t-on "la maison de Zayd" ?</p></div><div class="options-grid"><button class="option-btn" data-correct="true" onclick="checkAnswer(this)"><span class="arabic">بَيْتُ زَيْدٍ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">البَيْتُ زَيْدٍ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">بَيْتٌ زَيْدٌ</span></button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">بَيْتُ زَيْدُ</span></button></div><div class="feedback-message" id="feedback"></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Le مُضَاف varie selon la phrase</h3><div class="theory-content"><div class="grammar-box"><h4>📝 Position du مُضَاف</h4><p>Le <span class="arabic">مُضَاف</span> prend le cas que demande sa fonction :</p></div><div class="arabic-example"><p class="arabic" style="font-size:1.5rem;">هَذَا <span style="color:var(--success);">كِتَابُ</span> الطَّالِبِ</p><p class="arabic-translation">Ceci est le livre de l'étudiant</p><p style="font-size:0.9rem;color:var(--success);">كِتَابُ = مُضَاف مَرْفُوع (sujet)</p></div><div class="arabic-example" style="margin-top:1rem;"><p class="arabic" style="font-size:1.5rem;">زَيْدٌ فِي <span style="color:var(--accent);">بَيْتِ</span> يَاسِرٍ</p><p class="arabic-translation">Zayd est dans la maison de Yasser</p><p style="font-size:0.9rem;color:var(--accent);">بَيْتِ = مُضَاف مَجْرُور (après في)</p></div></div></div>` },
            { type: "theory", content: `<div class="theory-section"><h3 class="theory-title">📚 Vocabulaire de l'annexion</h3><div class="theory-content"><table class="vocab-table"><thead><tr><th>Annexion</th><th>Traduction</th></tr></thead><tbody><tr><td class="vocab-arabic arabic">كِتَابُ اللهِ</td><td>Le Livre d'Allah (le Coran)</td></tr><tr><td class="vocab-arabic arabic">رَسُولُ اللهِ</td><td>Le Messager d'Allah</td></tr><tr><td class="vocab-arabic arabic">بَيْتُ المُدَرِّسِ</td><td>La maison de l'enseignant</td></tr><tr><td class="vocab-arabic arabic">قَلَمُ الطَّالِبِ</td><td>Le stylo de l'étudiant</td></tr><tr><td class="vocab-arabic arabic">اِبْنُ عَبَّاسٍ</td><td>Le fils de Abbas (Ibn Abbas)</td></tr><tr><td class="vocab-arabic arabic">بِنْتُ حَامِدٍ</td><td>La fille de Hamid</td></tr></tbody></table></div></div>` },
            { type: "exercise", content: `<div class="exercise-section"><h3 class="exercise-title">🎯 Exercice final</h3><div class="exercise-question"><p>Dans <span class="arabic" style="font-size:1.5rem;color:var(--primary);">سَيَّارَةُ المُدِيرِ</span> (la voiture du directeur), quel est le cas de المُدِيرِ ?</p></div><div class="options-grid"><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">مَرْفُوعٌ</span> car c'est le sujet</button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)"><span class="arabic">مَنْصُوبٌ</span> car c'est le COD</button><button class="option-btn" data-correct="true" onclick="checkAnswer(this)"><span class="arabic">مَجْرُورٌ</span> car c'est مُضَاف إِلَيْهِ</button><button class="option-btn" data-correct="false" onclick="checkAnswer(this)">Aucun cas particulier</button></div><div class="feedback-message" id="feedback"></div></div>` }
        ]
    }
};

// Functions
function updateXPDisplay() {
    document.getElementById('totalXP').textContent = totalXP + ' XP';
}

function updateProgressBars() {
    const totalLessons = Object.keys(lessonsData).length;
    const completedLessons = Object.keys(lessonsProgress).filter(k => lessonsProgress[k] === 100).length;
    const globalPercentage = (completedLessons / totalLessons) * 100;
    document.getElementById('globalProgress').style.width = globalPercentage + '%';
    
    for (let i = 1; i <= totalLessons; i++) {
        const el = document.getElementById('lesson' + i + 'Progress');
        if (el) el.style.width = (lessonsProgress[i] || 0) + '%';
    }
}

function startLesson(lessonNum) {
    currentLesson = lessonNum;
    currentStep = 0;
    const lesson = lessonsData[lessonNum];
    document.getElementById('lessonTitle').textContent = lesson.title;
    document.getElementById('lessonsGrid').style.display = 'none';
    document.getElementById('learningContainer').classList.add('active');
    renderStepIndicator();
    renderStep();
}

function renderStepIndicator() {
    const container = document.getElementById('stepIndicator');
    const steps = lessonsData[currentLesson].steps;
    container.innerHTML = steps.map((_, i) => 
        `<div class="step-dot ${i === currentStep ? 'active' : ''} ${i < currentStep ? 'completed' : ''}"></div>`
    ).join('');
}

function renderStep() {
    const step = lessonsData[currentLesson].steps[currentStep];
    document.getElementById('lessonContent').innerHTML = step.content;
    makeSpeakable(document.getElementById('lessonContent'));
    renderStepIndicator();
    document.getElementById('prevBtn').disabled = currentStep === 0;
    const isLast = currentStep === lessonsData[currentLesson].steps.length - 1;
    document.getElementById('nextBtn').textContent = isLast ? 'Terminer ✓' : 'Suivant →';
}

function nextStep() {
    const steps = lessonsData[currentLesson].steps;
    if (currentStep < steps.length - 1) {
        currentStep++;
        renderStep();
    } else {
        completeLesson();
    }
}

function prevStep() {
    if (currentStep > 0) {
        currentStep--;
        renderStep();
    }
}

function checkAnswer(btn) {
    const isCorrect = btn.dataset.correct === 'true';
    const feedback = document.getElementById('feedback');
    const allBtns = btn.parentElement.querySelectorAll('.option-btn');
    
    allBtns.forEach(b => b.style.pointerEvents = 'none');
    
    if (isCorrect) {
        btn.classList.add('correct');
        feedback.textContent = '✅ Excellent ! Bonne réponse !';
        feedback.className = 'feedback-message show success';
    } else {
        btn.classList.add('incorrect');
        allBtns.forEach(b => { if (b.dataset.correct === 'true') b.classList.add('correct'); });
        feedback.textContent = '❌ Pas tout à fait. Regarde la bonne réponse.';
        feedback.className = 'feedback-message show error';
    }
}

function completeLesson() {
    const lesson = lessonsData[currentLesson];
    if (!lessonsProgress[currentLesson] || lessonsProgress[currentLesson] < 100) {
        totalXP += lesson.xp;
        lessonsProgress[currentLesson] = 100;
        localStorage.setItem('arabicXP', totalXP);
        localStorage.setItem('lessonsProgress', JSON.stringify(lessonsProgress));
    }
    document.getElementById('modalXP').textContent = '+' + lesson.xp + ' XP';
    document.getElementById('completionModal').classList.add('show');
    updateXPDisplay();
    updateProgressBars();
}

function closeModal() {
    document.getElementById('completionModal').classList.remove('show');
    closeLesson();
}

function closeLesson() {
    document.getElementById('learningContainer').classList.remove('active');
    document.getElementById('lessonsGrid').style.display = 'grid';
    currentLesson = null;
    currentStep = 0;
}